import Loader from '@/components/Loader';
import { GetServerSideProps } from 'next';
import { getSession, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import Image from 'next/image';

export default function SetProfile() {
    let session = useSession();

    if (session.status === 'loading') {
        return <Loader />;
    }

    if (!session) {
        return <Loader />;
    }

    return (
        <div className="bg-gray-800 min-h-screen">
            <Head>
                <title>Next Auth</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-gray-800 min-h-screen flex justify-center items-center text-white">
                <div className="w-[320px] mx-auto overflow-auto">
                    <h1 className="text-white text-xl font-bold text-center mb-3">
                        Next auth user
                    </h1>
                    <div className="flex items-center border-2 border-blue-800 rounded">
                        <Image
                            className="rounded"
                            src={session?.data?.user?.image}
                            height={79}
                            width={79}
                            priority
                            alt={session.data?.user?.name ?? 'guest-user'}
                        />
                    </div>
                    {session?.status === 'authenticated' ? (
                        <button
                            onClick={() => signOut()}
                            className="rounded border w-full mt-3 px-5 py-3 border-blue-500 bg-blue-800 text-white hover:bg-blue-900 flex items-center justify-center"
                        >
                            Logout
                        </button>
                    ) : (
                        <Link
                            href="/login"
                            className="rounded border mt-3 px-5 py-3 border-blue-500 bg-blue-800 text-white hover:bg-blue-900 flex items-center justify-center"
                        >
                            Login
                        </Link>
                    )}
                    <Link
                        href="/"
                        className="rounded border mt-3 px-5 py-3 border-blue-500 bg-blue-800 text-white hover:bg-blue-900 flex items-center justify-center"
                    >
                        Go home
                    </Link>
                </div>
            </main>
        </div>
    );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            },
        };
    }

    return {
        props: {
            session,
        },
    };
};
