import Loader from '@/components/Loader';
import { Fetcher } from '@/utils/Fetcher';
import { signIn, useSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import useSWR from 'swr';

export default function SignUp() {
    const router = useRouter();
    const session = useSession();
    let { data: userData } = useSWR(
        session?.status === 'authenticated' ? '/auth/user' : null,
        Fetcher,
    );

    const googleLogin = async () => {
        try {
            let data = await signIn(
                'google',
                {
                    callbackUrl: process.env.NEXTAUTH_URL,
                },
                { prompt: 'login' },
            );

            console.log(data);
        } catch (error) {
            console.log(error);
        }
    };

    const facebookLogin = async () => {
        try {
            await signIn('facebook', { callbackUrl: process.env.NEXTAUTH_URL });
        } catch (error) {
            console.log(error);
        }
    };

    if (
        session?.status === 'authenticated' &&
        userData &&
        userData?.response?.email === session?.data?.user?.email
    ) {
        router.push('/');
    }
    if (
        session?.status === 'unauthenticated' ||
        (userData && userData?.response?.email !== session?.data?.user?.email)
    ) {
        return (
            <>
                <Head>
                    <title>Next Auth</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="bg-gray-800 min-h-screen flex justify-center items-center text-white">
                    <div className="w-[320px] mx-auto">
                        <h1 className="text-center text-2xl font-bold">Next Auth Sign Up</h1>

                        <button
                            onClick={() => googleLogin()}
                            className="mt-3 rounded border w-full py-3 border-blue-500 bg-blue-800 text-white hover:bg-blue-900 flex items-center justify-center"
                        >
                            <Image
                                src="/images/google.svg"
                                height={18}
                                width={18}
                                alt="google-icon"
                            />
                            <span className="ml-2">Sign up with google</span>
                        </button>

                        <button
                            onClick={() => facebookLogin()}
                            className="mt-3 rounded border w-full py-3 border-blue-500 bg-blue-800 text-white hover:bg-blue-900 flex items-center justify-center"
                        >
                            <Image
                                src="https://img.icons8.com/fluency/512/facebook-new.png"
                                height={24}
                                width={24}
                                alt="facebook-icon"
                            />
                            <span className="ml-2">Sign up with facebook</span>
                        </button>
                        <div className="flex items-center mt-3">
                            <div className="w-full h-px bg-gray-200 rounded mt-px" />
                            <span className="text-white font-bold text-base px-2">or</span>
                            <div className="w-full h-px bg-gray-200 rounded mt-px" />
                        </div>
                        <div className="flex justify-between">
                            <button
                                onClick={() => router.push('/')}
                                className="my-3 mr-1.5 text-center rounded border w-full py-3 border-blue-500 bg-blue-800 text-white hover:bg-blue-900"
                            >
                                Back
                            </button>
                            <button
                                onClick={() => router.push('/login')}
                                className="my-3 ml-1.5 rounded border w-full py-3 border-blue-500 bg-blue-800 text-white hover:bg-blue-900"
                            >
                                Sign in
                            </button>
                        </div>
                    </div>
                </div>
            </>
        );
    }
    return <Loader />;
}
